#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jun 22 11:57:17 2018

@author: ajdavis
"""

import thinkstats2
import thinkplot
import nsfg
import probability
import cumulative
import numpy as np
import analytic
import scipy.stats
import brfss
import pandas


# Q1.
# =============================================================================
# Exercise 4   Using the variable totalwgt_lb, investigate whether first babies 
# are lighter or heavier than others. Compute Cohen’s d to quantify the 
# difference between the groups. How does it compare to the difference in 
# pregnancy length?
# =============================================================================

preg = nsfg.ReadFemPreg()
#preg = nsfg.CleanFemPreg(preg)

live = preg[preg.outcome == 1]

firsts = live[live.birthord == 1]
others = live[live.birthord != 1]

def CohenEffectSize(group1, group2):
    diff = group1.mean() - group2.mean()

    var1 = group1.var()
    var2 = group2.var()
    n1, n2 = len(group1), len(group2)

    pooled_var = (n1 * var1 + n2 * var2) / (n1 + n2)
    d = diff / math.sqrt(pooled_var)
    return d

es_wgt = CohenEffectSize(firsts['totalwgt_lb'], others['totalwgt_lb'])
es_lngth = CohenEffectSize(firsts['prglngth'], others['prglngth'])

# Q2.
# =============================================================================
# Exercise 1   Something like the class size paradox appears if you survey 
# children and ask how many children are in their family. Families with many 
# children are more likely to appear in your sample, and families with no 
# children have no chance to be in the sample.
# Use the NSFG respondent variable NUMKDHH to construct the actual distribution 
# for the number of children under 18 in the household.
# 
# Now compute the biased distribution we would see if we surveyed the children 
# and asked them how many children under 18 (including themselves) are in their 
# household.
# 
# Plot the actual and biased distributions, and compute their means. As a 
# starting place, you can use chap03ex.ipynb.
# =============================================================================

resp = nsfg.ReadFemResp()
pmf = thinkstats2.Pmf(resp['numkdhh'], label='actual')

biased_pmf = BiasPmf(pmf, label='observed')
thinkplot.PrePlot(2)
thinkplot.Pmfs([pmf, biased_pmf])
thinkplot.Show(xlabel='class size', ylabel='PMF')
print('mean', pmf.Mean())
print('mean', biased_pmf.Mean())


# Q3.
# =============================================================================
# Exercise 2   The numbers generated by random.random are supposed to be uniform 
# between 0 and 1; that is, every value in the range should have the same 
# probability.
# Generate 1000 numbers from random.random and plot their PMF and CDF. Is the 
# distribution uniform?
# =============================================================================

rand_dist = np.random.random(1000) # create random distribution

#plot pmf
pmf = thinkstats2.Pmf(rand_dist)
thinkplot.Pmfs([pmf])



cdf = thinkstats2.Cdf(rand_dist, label='rand_dist')
ranks = [cdf.PercentileRank(x) for x in rand_dist]
rank_cdf = thinkstats2.Cdf(ranks)
thinkplot.Cdf(rank_cdf)
thinkplot.Show(xlabel='percentile rank', ylabel='CDF')

# Q4.
# =============================================================================
# Exercise 1   In the BRFSS (see Section 5.4), the distribution of heights is 
# roughly normal with parameters µ = 178 cm and σ = 7.7 cm for men, and µ = 163 
# cm and σ = 7.3 cm for women.
# In order to join Blue Man Group, you have to be male between 5’10” and 6’1” 
# (see http://bluemancasting.com). What percentage of the U.S. male population 
# is in this range? Hint: use scipy.stats.norm.cdf.
# =============================================================================

df = ReadBrfss()
df.sex.value_counts()
w = df[df.sex == 2]
m = df[df.sex == 1]
scipy.stats.norm.cdf(m)

# Q5.
# =============================================================================
# Exercise 1   In the BRFSS (see Section 5.4), the distribution of heights is 
# roughly normal with parameters µ = 178 cm and σ = 7.7 cm for men, and µ = 163 
# cm and σ = 7.3 cm for women.
# In order to join Blue Man Group, you have to be male between 5’10” and 6’1” 
# (see http://bluemancasting.com). What percentage of the U.S. male population 
# is in this range? Hint: use scipy.stats.norm.cdf.
# =============================================================================

mu = 178
sigma = 7.7

dist = scipy.stats.norm(loc=mu, scale = sigma)
type(dist)

dist.mean()
dist.cdf(177.8)
dist.cdf(185.4)

blueman_perc = dist.cdf(185.4) - dist.cdf(177.8)
